version: "3.9"


services:
  database:
    container_name: database
    image: cockroachdb/cockroach:v23.1.8
    command: start-single-node --insecure --http-addr 0.0.0.0
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "26257:26257"
      - "8080:8080"
